# Generated by Django 2.1.2 on 2018-10-21 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do evento')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='dono do evento')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='MiniCurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do minicurso')),
                ('duracao', models.TimeField(verbose_name='duração')),
                ('data', models.DateField(verbose_name='data da atividade')),
                ('horario', models.TimeField(verbose_name='hora da atividade')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='eventos.Evento', verbose_name='evento')),
                ('inscritos', models.ManyToManyField(blank=True, related_name='inscrito', to=settings.AUTH_USER_MODEL, verbose_name='inscritos')),
            ],
            options={
                'verbose_name': 'minicurso',
                'verbose_name_plural': 'minicursos',
            },
        ),
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome da palestra')),
                ('duracao', models.TimeField(verbose_name='duração')),
                ('data', models.DateField(verbose_name='data da atividade')),
                ('horario', models.TimeField(verbose_name='hora da atividade')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventos.Evento', verbose_name='evento')),
                ('inscritos', models.ManyToManyField(blank=True, related_name='inscritos', to=settings.AUTH_USER_MODEL, verbose_name='inscritos')),
            ],
            options={
                'verbose_name': 'palestra',
                'verbose_name_plural': 'palestras',
            },
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do palestrante')),
            ],
            options={
                'verbose_name': 'palestrante',
                'verbose_name_plural': 'palestrantes',
            },
        ),
        migrations.AddField(
            model_name='palestra',
            name='palestrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palestrante', to='eventos.Palestrante', verbose_name='palestrante'),
        ),
        migrations.AddField(
            model_name='minicurso',
            name='palestrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palestrantes', to='eventos.Palestrante', verbose_name='palestrante'),
        ),
    ]
